spring.application.name=smart-campus-backend
server.port=8080

spring.data.mongodb.uri=mongodb+srv://sandarukaushan999_db_user:rs8HPpDDlIoHGM6T@campusoperationshub.zbci1vn.mongodb.net/smartcampusdb?retryWrites=true&w=majority

app.security.jwt-secret=mySuperSecretKey123456
app.security.jwt-expiration-seconds=86400