spring.application.name=smart-campus-backend
server.port=${SERVER_PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/smartcampusdb}

app.security.jwt-secret=${JWT_SECRET:change-this-secret-key-in-production}
app.security.jwt-expiration-seconds=86400
